Update docs
redhat-exd-rebuilds/mintmaker-docs pull request #7
Opened 2024-08-08 22:22 UTC by FernandesMF

This PR updates the MintMaker docs. There are new topics, and also some previous topics have been moved around. I made this reorganization because I felt the new topics did not quite fit in the old organization.

Here's a temptative list of changes:
- reorganization of the topics:
    - 'supported managers' now goes after 'configurations'
    - sections on offboarding and `updateNotScheduled`, previously under 'configuration', are now under 'advanced topics'
- moved the section on how to create custom configs to its own page and expanded a bit
- introduction is also expanded
- new section on how to point mintmaker to custom container/docker files
- new section about automerging under 'advanced topics'

I believe I haven't been consistent regarding the Renovate vs MintMaker nomenclature, so please be extra harsh about it! 😂 

Since there was a bit of moving around, I also suggest you serve the book as it is in this branch to have a better grasp of the new organization. I guess that is hard to check from the markdowns alone.

I'm also not sure about grouping several topics under 'advanced topics'. Perhaps they deserve their own page as well... let me know what you think!

Thanks! 😁

2024-08-12 07:06 UTC, staticf0x requested changes
Looks good, it makes sense to have it organized this way, thanks @FernandesMF. My comments are mostly just about nitpicks or typos. One thing I noticed though, did you intend on keeping the Supported managers page or not? It's still in the repo, but I remember there was a discussion about removing it, so just asking.

2024-08-12 07:06 UTC, staticf0x commented on src/user/advanced_topics.md
> +- the repositorie's CI pipeline ran successfully succeeds, and
```suggestion
- the repository CI pipeline ran successfully, and
```

2024-08-12 07:06 UTC, staticf0x commented on src/user/advanced_topics.md
> +__[10:01am]__ | PR for dependency `xyz` in is filed
```suggestion
__[10:01am]__ | PR for dependency `xyz` is filed
```

2024-08-12 07:06 UTC, staticf0x commented on src/user/advanced_topics.md
> +__[11:02am]__ | PR for dependency `xyz` is automerged
```suggestion
__[12:00pm]__ | MintMaker run 2 starts
__[12:01pm]__ | PR for dependency `xyz` is detected
__[12:02pm]__ | PR for dependency `xyz` is automerged
```

I would prefer to use the actual times in current MintMaker so we don't give users hope that it runs every hour :smile:

2024-08-12 20:17 UTC, FernandesMF commented on src/user/introduction.md
> +RPM lockfiles.
Done!

2024-08-12 20:17 UTC, FernandesMF commented on src/user/custom_containerfiles.md
> +# Custom Container Files
Done!

2024-08-12 20:17 UTC, FernandesMF commented on src/SUMMARY.md
> +- [Custom Container files](./user/custom_containerfiles.md)
Done!

2024-08-12 20:17 UTC, FernandesMF commented on src/user/advanced_topics.md
> +__[10:01am]__ | PR for dependency `xyz` in is filed
Done!

2024-08-12 20:18 UTC, FernandesMF commented on src/user/advanced_topics.md
> +__[11:02am]__ | PR for dependency `xyz` is automerged
Very good point indeed 😂

2024-08-12 20:18 UTC, FernandesMF commented on src/user/advanced_topics.md
> +# Advanced Topics
Done!

2024-08-12 20:21 UTC, FernandesMF commented
Thank you for the thorough review, @staticf0x! Good catches, and good point about the "fake schedule" 😂 

About the managers page, I was forgetting about it! I removed it from `summary.md`, but I left the file in the repo still. I believe it might be useful in case we want to rewrite that section, maybe it is an okay starting point.

Could you have another look? Thanks!

2024-08-13 13:59 UTC, FernandesMF commented
You're absolutely right, @staticf0x! I'll remove that file and proceed with the merge. Thanks a lot! 😁

2024-08-13 14:10 UTC, merged